### ISSUE TITLE
Update with stabilized `core::arch` modules

### ISSUE THREAD

**Issue by althonos** [gnzlbg/bitintr#7]
Hi !

First of all thanks for that library, it's been super easy adding BMI2 support for a decompression algorithm I needed, and that made the code 3x faster on x86 without having to worry about the target arch in my own code.

That being said, I noticed some the use of `core::arch` was being feature-gated behind an `unstable` config flag, even though the `core::arch::x86` and `core::arch::x86_64` have been stabilized. 

This would make it possible to provide support for `x86` and `x86_64` intrinsincs on stable builds, whereas currently it falls back to the default implementation.

**Comment by gnzlbg** [comment]
@althonos thanks for the feedback. I always wanted to revisit this library but because I use nightly it wasn't really a priority. Let me see what I can do here.

**Comment by gnzlbg** [comment]
Version 0.3 has been released with this fixed.
